import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { MostRecentArticles } from '../components/MostRecentArticles/MostRecentArticles'
import { MoreArticles } from '../components/MoreArticles/MoreArticles'
import { Categories } from '../components/Categories/Categories'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <MostRecentArticles/>
        <div className={styles.more_content}>
          <MoreArticles/>
          <Categories/>
        </div>
      </div>
    </div>
  )
}

export default Home
